###################################################################
# TLS Configuration for Self-Signed Certificates
###################################################################

tls:
  certificates:
    - certFile: /certs/stackored-wildcard.crt
      keyFile: /certs/stackored-wildcard.key

  stores:
    default:
      defaultCertificate:
        certFile: /certs/stackored-wildcard.crt
        keyFile: /certs/stackored-wildcard.key
