http:
  routers:
    project1-router:
      rule: "Host(`project1.loc`)"
      service: project1-service

  services:
    project1-service:
      loadBalancer:
        servers:
          - url: "http://project1-php:9000"